version: '3'
services:

  app:
    build: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/sns_app
      - public-data:/sns_app/public
      - tmp-data:/sns_app/tmp
      - log-data:/sns_app/log
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "4306:3306"

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/sns_app/public
      - tmp-data:/sns_app/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

